# mail configuration
address: "smtp.gmail.com" # can change adress for yahoo or other
mail_username: "" # username
mail_password: "" # password
# other configuration like to mail and subject.
to_mail: "" # to mail
mail_subject: "" # subject
